datelastupdated: March 2023
fullnameofperson: Amanda Miotto
selfIdentification: eResearch Analyst and lover of Science and IT
remote_theme: https://github.com/sharu725/online-cv
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll
- jekyll-gist
- jekyll-sitemap
- jekyll-seo-tag
- rake
title: [The title of your site]

# from theme
analytics: G-3ZRKRRS1WT
description: A beautiful Jekyll theme for creating resume
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
