datelastupdated: March 2023
fullnameofperson: Amanda Miotto
selfIdentification: Problem solver in the data & tech space, who enjoys sharing knowledge

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll
- jekyll-gist
- jekyll-sitemap
- jekyll-seo-tag
- rake
- jekyll-analytics
- datatable
title: [The title of your site]
colour1bg: "#e2dadb"
colour2sdbr: "#a2a7a5"
linkedin: amanda-miotto-94b8ba13/
github: amandamiotto
twitter: amandamiottogu
