datelastupdated: March 2023
fullnameofperson: Amanda Miotto
selfIdentification: Problem solver in the data & tech space, who enjoys sharing knowledge

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll
- jekyll-gist
- jekyll-sitemap
- jekyll-seo-tag
- rake
- jekyll-analytics
- datatable
title: [CV of Amanda Miotto]
colour1bg: "#E0F2E9" #light honeydue
colour2sdbr: "#2B4141"  # Dark Slate Grey
colour3Misc: "#702632"  # Wine
colour4Misc: "#F7A072" # atomic tangerine
colour5Misc: "#2B0504" # black bean
textColouroverCol1: black
textColouroverCol2: white
textColouroverCol3: black
textColouroverCol4: white
textColouroverCol5: white
linkedin: amanda-miotto-94b8ba13/
github: amandamiotto
twitter: amandamiottogu
email: amcg@c45y.com
