datelastupdated: March 2023
fullnameofperson: Amanda Miotto
selfIdentification: Problem solver who enjoys working with people and sharing knowledge
#remote_theme: https://github.com/sharu725/online-cv
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll
- jekyll-gist
- jekyll-sitemap
- jekyll-seo-tag
- rake
- jekyll-analytics
title: [The title of your site]

jekyll_analytics:
  GoogleAnalytics:          
    id: G-3ZRKRRS1WT 

linkedin: amanda-miotto-94b8ba13/
github: amandamiotto
twitter: amandamiottogu
email: 

Colour1bg:
Colour2sdbr:
Colour3accent:
