datelastupdated: March 2023
fullnameofperson: Amanda Miotto
selfIdentification: eResearch Analyst and lover of Science and IT
remote_theme: cotes2020/jekyll-theme-chirpy
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [The title of your site]
description: [A short description of your site's purpose]
show_downloads: ["false"]
google_analytics: []
